// llama-vlm-kld — on-the-fly paired fidelity metrics for VLM evaluation.
//
// Loads TWO (model, mmproj) pairs — a reference (e.g. F16) and a candidate
// (e.g. Q4_K_M) — runs the SAME teacher-forced prompt+answer through both, and
// computes per-answer-token divergence metrics from the two full-vocab logit
// rows while they are still in memory. Only the metrics are written to disk:
// 68 bytes/position instead of vocab * 4 bytes/position of dense fp32 logits
// (~14,000x smaller at vocab ~152k); every metric covers the full vocabulary.
//
// Deliberately a STANDALONE module, independent of vlm-score.cpp (which dumps
// logits for offline comparison): the two tools answer different questions and
// reviewing/maintaining them separately keeps each contract small. The small
// helpers shared with vlm-score.cpp (stderr prefixing, file slurping, token
// reading) are duplicated here on purpose.
//
// Does NOT sample. Does NOT generate. Pure dual forward + metric extraction.
//
// CLI:
//   --ref-model <gguf>                 Reference LLM weights
//   --ref-mmproj <gguf>                Reference vision projector
//   --cand-model <gguf>                Candidate LLM weights
//   --cand-mmproj <gguf>               Candidate vision projector
//   --image <path>                     Image file (repeatable; one --image per
//                                      <__media__> marker in --formatted-chat)
//   --formatted-chat <path>            File containing the HF-rendered chat string
//   --tokens-in <path>                 Binary file: int32[L] of full input_ids
//   --n-prefill <int>                  First answer-token index (must match HF stored value)
//   --output-metrics <path>            Output binary file (VLMK records)
//   --manifest <jsonl>                 Batch mode: JSONL entries with images,
//                                      formatted_chat, tokens_in, n_prefill,
//                                      output_metrics. Loads both models once.
//                                      Takes precedence: the per-row flags
//                                      above are ignored when given.
//   --image-min-tokens <int>           Lower bound; -1 = use model metadata (default -1)
//   --image-max-tokens <int>           Upper bound; -1 = use model metadata (default -1)
//   --num-eval-tokens <int>            Stop teacher-forcing after this many answer
//                                      positions (-1 = all, default; clamped to
//                                      L - n_prefill)
//   -ngl <int>                         GPU layers to offload, per model (default 99)
//   -c <int>                           Context size, per model (default 32768)
//   -b <int>                           Logical batch size for prefill (default 2048)
//   -ub <int>                          Physical micro-batch for prefill; also the
//                                      default teacher-forcing chunk size (default 2048)
//   --tf-chunk <int>                   Teacher-forcing chunk size, decoupled from -ub
//                                      (default -1 = follow -ub). Same numerics caveat
//                                      as vlm-score: batched chunks shift logits by FP
//                                      non-associativity, so runs that must be
//                                      comparable (e.g. ref-vs-A and ref-vs-B sharing
//                                      the same reference) MUST use the same --tf-chunk.
//   -t <int>                           CPU threads for llama decode and mtmd image
//                                      encode (default -1 = ggml's compiled default;
//                                      irrelevant for fully-offloaded GPU runs)
//   --metric-threads <int>             Threads for the per-position metric kernel
//                                      (default -1 = hardware concurrency)
//   --flash-attn                       Require flash attention
//   --no-flash-attn                    Disable flash attention (default: auto)
//   --swa-full                         Full-size KV cache for sliding-window layers
//                                      (the llama_context default). Off by default:
//                                      SWA layers allocate only their window, like
//                                      the common llama.cpp CLI. Same attention math
//                                      either way; results differ by FP reordering
//                                      only, so runs that must be comparable use the
//                                      same setting (recorded in collect_meta.json).
//   --add-special                      mtmd add_special=true for the prefix (rows generated by
//                                      llama-server; the manifest key "add_special" sets it per row)
//   --allow-prefix-drift               Image-span drift vs tokens_in only warns (default: error, like
//                                      any text-token mismatch); --require-prefix-match restores the default
//   --allow-n-past-drift               Do not hard-fail when the two sides end
//                                      prefill at DIFFERENT llama.cpp positions.
//                                      That drift means the same images became
//                                      different numbers of embeddings, so every
//                                      scored position is conditioned on a
//                                      different prefix; use only when the drift
//                                      itself is what you are measuring.
//   --allow-vocab-attr-mismatch        Accept per-token ATTRIBUTE differences
//                                      (token type / EOG flags) between the two
//                                      vocabs; token texts must still match id
//                                      by id. For same-base-model conversions
//                                      whose metadata disagrees (e.g. which id
//                                      is <eos>). Every mismatch is logged.
//   --self-test                        Run the metric-kernel self test (no models
//                                      needed) and exit 0/1
//   --vlmk-version                     Print the VLMK format version this binary
//                                      writes (stdout, integer) and exit 0; the
//                                      collectors preflight it against their
//                                      kld_metrics_io.VLMK_VERSION so a stale
//                                      build is refused before any GPU work
//
// NOTE: the answer region tokens[n_prefill:] is teacher-forced as pure text
// through BOTH models, so position i of the metrics aligns by answer index.
// Each side keeps its own KV cache / n_past. If the two ends of prefill land
// at DIFFERENT positions the run HARD-FAILS (--allow-n-past-drift overrides):
// the same images became different numbers of embeddings, so every scored
// position is conditioned on a different prefix and the paired metric would
// measure that rather than the quantization. Vision tokens must NOT appear
// after n_prefill. The two models MUST share a vocabulary; size, vocabulary
// type, and every token ID's text and attributes are checked at startup
// (--allow-vocab-attr-mismatch downgrades only the attribute check to a
// logged warning; texts remain strict).
//
// Output binary layout (LE on x86_64), magic "VLMK":
//   uint32_t magic = 0x564C4D4B                ("VLMK")
//   uint32_t version = 2                       (v1 = 40-byte records without ear)
//   uint32_t vocab_size                        (== llama_vocab_n_tokens, both models)
//   uint32_t n_positions                       (# answer tokens scored)
//   uint32_t n_prefill                         (HF ground-truth sequential
//                                              length, echoed from the manifest)
//   uint32_t n_past_actual                     (llama.cpp's OWN position count
//                                              after prefill -- the number that
//                                              actually moves when the vision
//                                              budget changes; 0 = not recorded,
//                                              i.e. written before this field)
// followed by n_positions packed records of 68 bytes:
//   float32 kld                                KL(p_ref || p_cand), nats
//   float32 reversed_kld                       KL(p_cand || p_ref), nats
//   float32 js_kld                             Jensen-Shannon divergence, nats
//   float32 nll_ref                            -log p_ref(target)
//   float32 nll_cand                           -log p_cand(target)
//   float32 entropy_ref                        -sum p_ref * log p_ref
//   float32 entropy_cand                       -sum p_cand * log p_cand
//   float32 ear                                sum min(p_ref, p_cand) = 1 - TV distance
//   float32 ear_20                             sum of min(p_ref, p_cand) over the reference's
//                                              top-20 slots, full-vocab probabilities (v4)
//   float32 ear_10 / ear_5                     same, top-10 / top-5 (v4)
//   float32 ear_20_normalized                  same slots, both rows renormalized on them
//                                              first (v4)
//   float32 ear_10_normalized / ear_5_normalized  same, top-10 / top-5 (v4)
//   int32   target                             teacher-forced target token id
//   int32   argmax_ref                         reference argmax token id
//   int32   argmax_cand                        candidate argmax token id
// All metrics are accumulated in float64 over the full vocab and stored as
// float32. Derivable downstream: same_top = (argmax_ref == argmax_cand),
// p(target) = exp(-nll), delta-p at target, perplexities = exp(mean nll).
// `ear` is the per-position Expected Acceptance Rate (arXiv:2605.02404): the
// probability-mass overlap sum_i min(p_ref(i), p_cand(i)) = 1 - d_TV, i.e. the
// max probability that optimally-coupled samples from the two distributions
// agree. Computed over the full vocabulary.
//
// Consumed by tools/skymizer/kld_metrics_io.py (load + lossless .npz
// conversion) and orchestrated over a dataset by tools/skymizer/collect_kld.py.
//
// Build registered in tools/skymizer/CMakeLists.txt.

#include "common.h"
#include "llama.h"
#include "llama-cpp.h"
#include "ggml.h"
#include "mtmd.h"
#include "mtmd-helper.h"

#include "nlohmann/json.hpp"

#include "skymizer-common.h"
#include "skymizer-vlmk-kernel.h"

#include <algorithm>
#include <atomic>
#include <cerrno>
#include <chrono>
#include <cmath>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <limits>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

#if defined(_WIN32)
#    include <io.h>
#else
#    include <unistd.h>
#endif

static constexpr uint32_t VLMK_MAGIC   = 0x564C4D4B; // "VLMK"
static constexpr uint32_t VLMK_VERSION = 4;          // v4: 68-byte records (+ ear_K and ear_K_normalized, K=20/10/5); v3 = 56, v2 = 44 (+ ear), v1 = 40


// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

struct vlm_kld_args {
    std::string ref_model_path;
    std::string ref_mmproj_path;
    std::string cand_model_path;
    std::string cand_mmproj_path;
    std::vector<std::string> image_paths;
    std::string formatted_chat_path;
    std::string tokens_in_path;
    std::string output_metrics_path;
    std::string manifest_path;
    int n_prefill = -1;
    int image_min_tokens = -1;   // -1 = use model metadata
    int image_max_tokens = -1;
    int num_eval_tokens = -1;    // -1 = score all answer positions
    int n_gpu_layers = 99;
    int n_ctx = 32768;
    int n_batch = 2048;
    int n_ubatch = 2048;
    int tf_chunk = -1;           // teacher-forcing chunk size; -1 = follow n_ubatch
    int n_threads = -1;
    int metric_threads = -1;     // -1 = hardware concurrency
    llama_flash_attn_type flash_attn_type = LLAMA_FLASH_ATTN_TYPE_AUTO;
    bool swa_full = false;             // see load_side()
    bool allow_n_past_drift = false;   // see the drift guard in score_one()
    bool add_special = false;          // mtmd_input_text.add_special for the prefix: manifest "add_special" or --add-special.
                                       // llama-server tokenizes /completion prompts with add_special=true, so rows generated
                                       // there (llm_reference_generator llamacpp_add_special) replay with true; HF/vLLM rows false.
    bool require_prefix_match = true;  // image-span drift between tokens_in and this mtmd's chunks is an error
                                       // (text-token mismatch always is); --allow-prefix-drift warns and scores anyway
    bool allow_vocab_attr_mismatch = false;  // see validate_vocab_id_mapping()
    bool self_test = false;
    bool print_vlmk_version = false;
};


static bool parse_args(int argc, char ** argv, vlm_kld_args & a) {
    bool saw_flash_attn = false;
    for (int i = 1; i < argc; ++i) {
        std::string k = argv[i];
        auto need = [&](const char * what) -> const char * {
            if (i + 1 >= argc) {
                fprintf(stderr, "missing value for %s\n", what);
                return nullptr;
            }
            return argv[++i];
        };
        auto need_int = [&](const char * what, int & out) {
            const char * v = need(what);
            return v != nullptr && parse_int_arg(what, v, out);
        };
        if      (k == "--ref-model")        { const char * v = need("--ref-model");        if (!v) return false; a.ref_model_path = v; }
        else if (k == "--ref-mmproj")       { const char * v = need("--ref-mmproj");       if (!v) return false; a.ref_mmproj_path = v; }
        else if (k == "--cand-model")       { const char * v = need("--cand-model");       if (!v) return false; a.cand_model_path = v; }
        else if (k == "--cand-mmproj")      { const char * v = need("--cand-mmproj");      if (!v) return false; a.cand_mmproj_path = v; }
        else if (k == "--image")            { const char * v = need("--image");            if (!v) return false; a.image_paths.emplace_back(v); }
        else if (k == "--formatted-chat")   { const char * v = need("--formatted-chat");   if (!v) return false; a.formatted_chat_path = v; }
        else if (k == "--tokens-in")        { const char * v = need("--tokens-in");        if (!v) return false; a.tokens_in_path = v; }
        else if (k == "--n-prefill")        { if (!need_int("--n-prefill",        a.n_prefill))        return false; }
        else if (k == "--output-metrics")   { const char * v = need("--output-metrics");   if (!v) return false; a.output_metrics_path = v; }
        else if (k == "--manifest")         { const char * v = need("--manifest");         if (!v) return false; a.manifest_path = v; }
        else if (k == "--image-min-tokens") { if (!need_int("--image-min-tokens", a.image_min_tokens)) return false; }
        else if (k == "--image-max-tokens") { if (!need_int("--image-max-tokens", a.image_max_tokens)) return false; }
        else if (k == "--num-eval-tokens")  { if (!need_int("--num-eval-tokens",  a.num_eval_tokens))  return false; }
        else if (k == "-ngl")               { if (!need_int("-ngl",               a.n_gpu_layers))     return false; }
        else if (k == "-c")                 { if (!need_int("-c",                 a.n_ctx))            return false; }
        else if (k == "-b")                 { if (!need_int("-b",                 a.n_batch))          return false; }
        else if (k == "-ub")                { if (!need_int("-ub",                a.n_ubatch))         return false; }
        else if (k == "--tf-chunk")         { if (!need_int("--tf-chunk",         a.tf_chunk))         return false; }
        else if (k == "-t")                 { if (!need_int("-t",                 a.n_threads))        return false; }
        else if (k == "--metric-threads")   { if (!need_int("--metric-threads",   a.metric_threads))   return false; }
        else if (k == "--flash-attn" || k == "--no-flash-attn") {
            if (saw_flash_attn) {
                fprintf(stderr, "flash-attention mode specified more than once\n");
                return false;
            }
            saw_flash_attn = true;
            a.flash_attn_type = k == "--flash-attn"
                ? LLAMA_FLASH_ATTN_TYPE_ENABLED
                : LLAMA_FLASH_ATTN_TYPE_DISABLED;
        }
        else if (k == "--swa-full")         { a.swa_full = true; }
        else if (k == "--allow-n-past-drift"){ a.allow_n_past_drift = true; }
        else if (k == "--add-special")       { a.add_special = true; }
        else if (k == "--require-prefix-match") { a.require_prefix_match = true; }
        else if (k == "--allow-prefix-drift")   { a.require_prefix_match = false; }
        else if (k == "--allow-vocab-attr-mismatch") { a.allow_vocab_attr_mismatch = true; }
        else if (k == "--self-test")        { a.self_test = true; }
        else if (k == "--vlmk-version")     { a.print_vlmk_version = true; }
        else if (k == "--help" || k == "-h") {
            fprintf(stderr, "see header of vlm-kld.cpp for CLI documentation\n");
            return false;
        } else {
            fprintf(stderr, "unknown argument: %s\n", k.c_str());
            return false;
        }
    }
    if (a.self_test || a.print_vlmk_version) {
        return true;   // no other arguments required
    }
    if (a.ref_model_path.empty() || a.ref_mmproj_path.empty() ||
        a.cand_model_path.empty() || a.cand_mmproj_path.empty()) {
        fprintf(stderr, "missing required arguments (run with --help)\n");
        return false;
    }
    if (a.manifest_path.empty()) {
        if (a.image_paths.empty() || a.formatted_chat_path.empty() ||
            a.tokens_in_path.empty() || a.output_metrics_path.empty() ||
            a.n_prefill < 0) {
            fprintf(stderr, "missing required arguments (run with --help)\n");
            return false;
        }
    }
    if (a.n_batch < 1 || a.n_ubatch < 1) {
        fprintf(stderr, "-b and -ub must be >= 1, got -b %d -ub %d\n", a.n_batch, a.n_ubatch);
        return false;
    }
    if (a.n_ubatch > a.n_batch) {
        fprintf(stderr, "-ub (%d) must be <= -b (%d)\n", a.n_ubatch, a.n_batch);
        return false;
    }
    if (a.tf_chunk != -1 && a.tf_chunk < 1) {
        fprintf(stderr, "--tf-chunk must be -1 (follow -ub) or >= 1, got %d\n", a.tf_chunk);
        return false;
    }
    if (a.num_eval_tokens != -1 && a.num_eval_tokens < 1) {
        fprintf(stderr, "num-eval-tokens must be -1 (all) or >= 1, got %d\n", a.num_eval_tokens);
        return false;
    }
    if (a.metric_threads != -1 && a.metric_threads < 1) {
        fprintf(stderr, "--metric-threads must be -1 (auto) or >= 1, got %d\n", a.metric_threads);
        return false;
    }
    return true;
}


// ---------------------------------------------------------------------------
// output writer
// ---------------------------------------------------------------------------

// Write the whole VLMK file at once (header + records), to <path>.tmp first,
// fsync, then atomically rename. Metrics are tiny (68 bytes/position), so
// unlike vlm-score's streaming vlms_writer there is no need to stream — a
// buffered single-shot write keeps the commit logic trivially reviewable and
// a crashed/partial run never leaves a complete-looking output behind.
static bool write_vlmk_file(
        const std::string & path,
        uint32_t n_vocab,
        uint32_t n_prefill,
        uint32_t n_past_actual,
        const std::vector<kld_record> & records,
        stderr_prefix * lp) {
    const std::string tmp_path = path + ".tmp";
    FILE * f = fopen(tmp_path.c_str(), "wb");
    if (f == nullptr) {
        prefixed_fprintf(lp, "failed to open output %s\n", tmp_path.c_str());
        return false;
    }
    bool ok = true;
    // Sixth word: llama.cpp's OWN position count after prefill, which is what
    // actually moves when the vision-token budget changes. n_prefill (fifth)
    // is the HF ground-truth sequential length echoed from the manifest and
    // for a VLM differs from it by design (M-RoPE). 0 = not recorded (files
    // written before this field existed).
    const uint32_t header[6] = {
        VLMK_MAGIC, VLMK_VERSION, n_vocab,
        (uint32_t) records.size(), n_prefill, n_past_actual,
    };
    ok = ok && fwrite(header, sizeof(header), 1, f) == 1;
    ok = ok && (records.empty() ||
                fwrite(records.data(), sizeof(kld_record), records.size(), f) == records.size());
    ok = ok && fflush(f) == 0;
#if defined(_WIN32)
    ok = ok && _commit(_fileno(f)) == 0;
#else
    ok = ok && fsync(fileno(f)) == 0;
#endif
    ok = (fclose(f) == 0) && ok;
    if (!ok) {
        prefixed_fprintf(lp, "failed writing %s: %s\n", tmp_path.c_str(), strerror(errno));
        std::remove(tmp_path.c_str());
        return false;
    }
    if (std::rename(tmp_path.c_str(), path.c_str()) != 0) {
        prefixed_fprintf(lp, "failed to rename %s -> %s: %s\n",
                         tmp_path.c_str(), path.c_str(), strerror(errno));
        std::remove(tmp_path.c_str());
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// manifest
// ---------------------------------------------------------------------------

struct manifest_entry {
    bool ok = false;
    std::string error;
    std::vector<std::string> image_paths;
    std::string formatted_chat_path;
    std::string tokens_in_path;
    std::string output_metrics_path;
    int n_prefill = -1;
    bool add_special = false;   // optional manifest key; see vlm_kld_args::add_special
};

static bool read_manifest(const std::string & path, std::vector<manifest_entry> & entries) {
    std::ifstream f(path);
    if (!f.is_open()) {
        fprintf(stderr, "failed to open manifest %s\n", path.c_str());
        return false;
    }

    std::string line;
    while (std::getline(f, line)) {
        manifest_entry entry;
        try {
            if (line.empty()) {
                throw std::runtime_error("empty manifest line");
            }
            const auto j = nlohmann::ordered_json::parse(line);
            if (!j.is_object()) {
                throw std::runtime_error("manifest line is not a JSON object");
            }
            if (!j.contains("images") || !j.at("images").is_array()) {
                throw std::runtime_error("missing or invalid images");
            }
            if (!j.contains("formatted_chat") || !j.at("formatted_chat").is_string()) {
                throw std::runtime_error("missing or invalid formatted_chat");
            }
            if (!j.contains("tokens_in") || !j.at("tokens_in").is_string()) {
                throw std::runtime_error("missing or invalid tokens_in");
            }
            if (!j.contains("n_prefill") || !j.at("n_prefill").is_number_integer()) {
                throw std::runtime_error("missing or invalid n_prefill");
            }
            if (!j.contains("output_metrics") || !j.at("output_metrics").is_string()) {
                throw std::runtime_error("missing or invalid output_metrics");
            }

            entry.image_paths          = j.at("images").get<std::vector<std::string>>();
            entry.formatted_chat_path  = j.at("formatted_chat").get<std::string>();
            entry.tokens_in_path       = j.at("tokens_in").get<std::string>();
            entry.n_prefill            = j.at("n_prefill").get<int>();
            entry.output_metrics_path  = j.at("output_metrics").get<std::string>();
            if (j.contains("add_special")) {
                if (!j.at("add_special").is_boolean()) {
                    throw std::runtime_error("add_special must be a boolean");
                }
                entry.add_special = j.at("add_special").get<bool>();
            }

            if (entry.formatted_chat_path.empty() || entry.tokens_in_path.empty() ||
                entry.output_metrics_path.empty()) {
                throw std::runtime_error("formatted_chat, tokens_in, and output_metrics must be non-empty");
            }
            entry.ok = true;
        } catch (const std::exception & e) {
            entry.error = e.what();
        }
        entries.push_back(std::move(entry));
    }

    if (entries.empty()) {
        fprintf(stderr, "manifest contains no entries: %s\n", path.c_str());
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// scoring
// ---------------------------------------------------------------------------

// One loaded (model, mmproj) pair plus its decode state for the current item.
struct model_side {
    const char *      tag;   // "ref" / "cand" (log labels)
    llama_model_ptr   model;
    llama_context_ptr lctx;
    mtmd::context_ptr vctx;
    llama_pos         n_past = 0;
};

static bool load_side(model_side & s, const char * tag,
                      const std::string & model_path, const std::string & mmproj_path,
                      const vlm_kld_args & args) {
    s.tag = tag;

    llama_model_params mparams = llama_model_default_params();
    mparams.n_gpu_layers = args.n_gpu_layers;
    s.model.reset(llama_model_load_from_file(model_path.c_str(), mparams));
    if (!s.model) {
        fprintf(stderr, "[%s] failed to load model %s\n", tag, model_path.c_str());
        return false;
    }

    llama_context_params cparams = llama_context_default_params();
    cparams.n_ctx     = args.n_ctx;
    cparams.n_batch   = args.n_batch;
    cparams.n_ubatch  = args.n_ubatch;
    cparams.n_seq_max = 1;
    // Set both thread knobs: multi-token ubatches (prefill + chunked teacher
    // forcing) use n_threads_batch, which would otherwise silently stay at
    // ggml's compiled default and ignore -t on CPU runs.
    cparams.n_threads       = args.n_threads;
    cparams.n_threads_batch = args.n_threads;
    cparams.flash_attn_type = args.flash_attn_type;
    // Default false matches the common llama.cpp CLI: the low-level context
    // default is full SWA, which allocates n_ctx cells for every sliding-window
    // layer, and this tool always uses a single sequential sequence. --swa-full
    // restores it for runs that must stay comparable with earlier collections.
    cparams.swa_full        = args.swa_full;
    s.lctx.reset(llama_init_from_model(s.model.get(), cparams));
    if (!s.lctx) {
        fprintf(stderr, "[%s] failed to create llama_context\n", tag);
        return false;
    }

    mtmd_context_params vparams = mtmd_context_params_default();
    vparams.use_gpu          = true;
    vparams.print_timings    = true;
    vparams.n_threads        = args.n_threads;
    vparams.flash_attn_type  = cparams.flash_attn_type;
    vparams.warmup           = true;
    vparams.image_min_tokens = args.image_min_tokens;
    vparams.image_max_tokens = args.image_max_tokens;
    s.vctx.reset(mtmd_init_from_file(mmproj_path.c_str(), s.model.get(), vparams));
    if (!s.vctx) {
        fprintf(stderr, "[%s] failed to load mmproj %s\n", tag, mmproj_path.c_str());
        return false;
    }
    return true;
}

// Prefill one side with the item's images + formatted chat (sequence 0 of its
// own context). Each side loads/tokenizes the images through its OWN mtmd
// context, so per-side vision-token counts (and hence n_past) may differ —
// that drift is part of what the metrics measure. logits_last=true keeps the
// last prompt position's logits (they predict answer token 0).
// Compare mtmd's tokenization of the prefix against the stored
// tokens_in[:n_prefill]. Text chunks must match token-for-token: a mismatch
// means this scorer is not scoring the prompt the answer was generated under
// (different tokenizer/vocab, wrong add_special, wrong formatted_chat) and is
// always fatal. Each image chunk must span exactly the stored run of identical
// placeholder ids at that position; a different span is vision-preprocessing
// drift between the generator's mtmd and this one (different build or
// --image-*-tokens budget). Drift is an error by default; --allow-prefix-drift
// downgrades it to a WARNING for runs where the drift itself is the object of
// study; the walk then realigns on the stored placeholder run so the text
// after the image (and later images) is still checked. Supported
// families always place wrapper text tokens between adjacent images, so a
// stored pad run never covers two images.
static bool check_prefix_against_tokens(const mtmd::input_chunks & chunks,
                                        const std::vector<int32_t> & tokens,
                                        int n_prefill,
                                        bool strict,
                                        const char * tag,
                                        stderr_prefix * lp) {
    const size_t n_chunks = mtmd_input_chunks_size(chunks.ptr.get());
    size_t pos = 0;
    size_t img_idx = 0;
    size_t n_drift = 0;
    for (size_t ci = 0; ci < n_chunks; ++ci) {
        const mtmd_input_chunk * c = mtmd_input_chunks_get(chunks.ptr.get(), ci);
        if (mtmd_input_chunk_get_type(c) == MTMD_INPUT_CHUNK_TYPE_TEXT) {
            size_t n = 0;
            const llama_token * t = mtmd_input_chunk_get_tokens_text(c, &n);
            for (size_t i = 0; i < n; ++i, ++pos) {
                const int32_t stored = pos < (size_t) n_prefill ? tokens[pos] : -1;
                if (stored != (int32_t) t[i]) {
                    prefixed_fprintf(lp,
                        "[%s] prefix mismatch at index %zu: stored=%d, this mtmd=%d (text chunk %zu). "
                        "The stored prompt is not what this scorer tokenized: check formatted_chat, "
                        "add_special (manifest \"add_special\" / --add-special) and that the GGUF "
                        "vocab matches the generator's.\n",
                        tag, pos, stored, (int) t[i], ci);
                    return false;
                }
            }
            continue;
        }
        const size_t n = mtmd_input_chunk_get_n_tokens(c);
        if (pos >= (size_t) n_prefill) {
            prefixed_fprintf(lp, "[%s] prefix mismatch: media chunk %zu starts at %zu, past n_prefill=%d\n",
                             tag, ci, pos, n_prefill);
            return false;
        }
        const int32_t pad = tokens[pos];
        size_t run = 0;
        while (pos + run < (size_t) n_prefill && tokens[pos + run] == pad) {
            ++run;
        }
        if (run != n) {
            prefixed_fprintf(lp,
                "[%s] %s: image %zu spans %zu embedding tokens in this scorer but %zu stored "
                "placeholder tokens (vision preprocessing drift between generator and scorer: "
                "different llama.cpp build or --image-min/max-tokens budget)\n",
                tag, strict ? "prefix mismatch" : "WARNING", img_idx, n, run);
            if (strict) {
                return false;
            }
            // Realign on the STORED run so the text after the image (and any
            // later image) is still checked; only the span length drifted.
            n_drift++;
            pos += run;
            ++img_idx;
            continue;
        }
        pos += n;
        ++img_idx;
    }
    if (pos != (size_t) n_prefill) {
        prefixed_fprintf(lp, "[%s] prefix mismatch: this mtmd produced %zu prefix tokens, stored n_prefill=%d\n",
                         tag, pos, n_prefill);
        return false;
    }
    if (n_drift > 0) {
        prefixed_fprintf(lp, "[%s] prefix check: text tokens match stored input_ids[:n_prefill]; %zu of %zu image "
                             "span%s drifted (allowed by --allow-prefix-drift)\n",
                         tag, n_drift, img_idx, img_idx == 1 ? "" : "s");
        return true;
    }
    prefixed_fprintf(lp, "[%s] prefix check: %zu tokens (%zu image span%s) match stored input_ids[:n_prefill]\n",
                     tag, pos, img_idx, img_idx == 1 ? "" : "s");
    return true;
}

static bool prefill_side(model_side & s,
                         const std::vector<std::string> & image_paths,
                         const std::string & formatted,
                         bool add_special,
                         const std::vector<int32_t> & tokens_full,
                         int n_prefill,
                         bool require_prefix_match,
                         int n_batch,
                         stderr_prefix * lp) {
    mtmd::bitmaps bmps_owned;
    bmps_owned.entries.reserve(image_paths.size());
    for (size_t i = 0; i < image_paths.size(); ++i) {
        auto media = mtmd_helper_bitmap_init_from_file(
            s.vctx.get(), image_paths[i].c_str(), false, mtmd_helper_init_opt_default());
        mtmd::bitmap b(media.bitmap);
        mtmd_helper::video_ptr video(media.video_ctx);
        if (video) {
            prefixed_fprintf(lp, "[%s] --image does not support video: %s\n", s.tag, image_paths[i].c_str());
            return false;
        }
        if (!b.ptr) {
            prefixed_fprintf(lp, "[%s] failed to load image[%zu] %s\n", s.tag, i, image_paths[i].c_str());
            return false;
        }
        bmps_owned.entries.push_back(std::move(b));
    }

    mtmd_input_text text{};
    text.text          = formatted.c_str();
    text.text_len      = formatted.size();
    text.add_special   = add_special;  // must replay the generator's setting (see vlm_kld_args::add_special)
    text.parse_special = true;

    mtmd::input_chunks chunks(mtmd_input_chunks_init());
    auto bmps = bmps_owned.c_ptr();
    int32_t rc = mtmd_tokenize(s.vctx.get(), chunks.ptr.get(), &text, bmps.data(), bmps.size());
    if (rc != 0) {
        prefixed_fprintf(lp,
                         "[%s] mtmd_tokenize failed (rc=%d); common cause: <__media__> marker count "
                         "in --formatted-chat must equal --image count (got %zu)\n",
                         s.tag, rc, bmps.size());
        return false;
    }
    if (!check_prefix_against_tokens(chunks, tokens_full, n_prefill, require_prefix_match, s.tag, lp)) {
        return false;
    }

    llama_pos new_n_past = 0;
    if (mtmd_helper_eval_chunks(
            s.vctx.get(), s.lctx.get(), chunks.ptr.get(), /*n_past=*/0, /*seq_id=*/0,
            /*n_batch=*/n_batch, /*logits_last=*/true, &new_n_past) != 0) {
        prefixed_fprintf(lp, "[%s] mtmd_helper_eval_chunks failed\n", s.tag);
        return false;
    }
    s.n_past = new_n_past;
    prefixed_fprintf(lp, "[%s] prefill done, n_past=%d\n", s.tag, (int) s.n_past);
    return true;
}

// Score one item: prefill both sides, teacher-force the shared answer tokens
// through both in chunks, and compute one kld_record per answer position from
// the two in-memory logit rows. Records are buffered (68 B/position) and the
// output is committed atomically at the end.
static bool score_one(
        const vlm_kld_args & args,
        model_side & ref,
        model_side & cand,
        int32_t n_vocab,
        int32_t n_batch,
        stderr_prefix * lp) {
    // Every item starts from clean KV on both sides (no-op on first use).
    llama_memory_clear(llama_get_memory(ref.lctx.get()),  false);
    llama_memory_clear(llama_get_memory(cand.lctx.get()), false);

    // --- read tokens ---
    std::vector<int32_t> tokens_full = read_tokens_bin(args.tokens_in_path, lp);
    if (tokens_full.empty()) {
        prefixed_fprintf(lp, "tokens-in is empty or unreadable\n");
        return false;
    }
    const int L = (int) tokens_full.size();
    if (args.n_prefill <= 0 || args.n_prefill >= L) {
        prefixed_fprintf(lp, "invalid n_prefill=%d for L=%d\n", args.n_prefill, L);
        return false;
    }
    for (int i = args.n_prefill; i < L; ++i) {
        if (tokens_full[i] < 0 || tokens_full[i] >= n_vocab) {
            prefixed_fprintf(lp, "answer token id %d at index %d out of vocab range [0, %d)\n",
                             tokens_full[i], i, n_vocab);
            return false;
        }
    }
    const int n_answer = L - args.n_prefill;
    const int n_eval = (args.num_eval_tokens > 0)
                       ? std::min(args.num_eval_tokens, n_answer)
                       : n_answer;
    prefixed_fprintf(lp, "tokens_full=%d, n_prefill=%d, n_answer=%d, n_eval=%d, vocab=%d, n_images=%zu\n",
                     L, args.n_prefill, n_answer, n_eval, n_vocab, args.image_paths.size());

    // --- prefill both sides ---
    const std::string formatted = slurp_file(args.formatted_chat_path, lp);
    if (formatted.empty()) {
        return false;
    }
    if (!prefill_side(ref,  args.image_paths, formatted, args.add_special, tokens_full, args.n_prefill,
                      args.require_prefix_match, n_batch, lp) ||
        !prefill_side(cand, args.image_paths, formatted, args.add_special, tokens_full, args.n_prefill,
                      args.require_prefix_match, n_batch, lp)) {
        return false;
    }

    // HARD FAIL on per-side prefill drift. The two sides tokenize the SAME
    // images through their OWN mtmd contexts, so a different vision-token
    // budget (image_min_tokens/image_max_tokens, or a differing mmproj GGUF
    // metadata default) turns the same image into a different number of
    // embeddings. Every scored position is then conditioned on a different
    // prefix, and the paired metric silently measures that instead of the
    // quantization. Nothing downstream can see it: n_prefill in the header is
    // the HF ground-truth echo, not this number.
    //
    // The previous behaviour was a stderr line and a completed dump, which
    // left NO on-disk witness of the drift. --allow-n-past-drift restores it
    // for the case where the drift itself is the object of study.
    if (ref.n_past != cand.n_past) {
        if (!args.allow_n_past_drift) {
            prefixed_fprintf(lp,
                "prefill drift: ref n_past=%d != cand n_past=%d. The two sides "
                "turned the same images into different numbers of embeddings, "
                "so every scored position is conditioned on a different "
                "prefix and the paired metrics would measure that, not the "
                "quantization. Check --image-min-tokens/--image-max-tokens and "
                "the two mmproj files' vision metadata. Pass "
                "--allow-n-past-drift only if the drift IS the measurement.\n",
                (int) ref.n_past, (int) cand.n_past);
            return false;
        }
        prefixed_fprintf(lp,
            "WARNING: prefill drift ref n_past=%d != cand n_past=%d, allowed "
            "by --allow-n-past-drift; the header records the REFERENCE side's "
            "count\n", (int) ref.n_past, (int) cand.n_past);
    }

    return kld_teacher_force_and_write(args, ref, cand, n_vocab, n_batch, n_eval,
                                       tokens_full, lp, write_vlmk_file);
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char ** argv) {
    vlm_kld_args args;
    if (!parse_args(argc, argv, args)) {
        return 1;
    }
    if (args.print_vlmk_version) {
        printf("%u\n", VLMK_VERSION);
        return 0;
    }
    if (args.self_test) {
        return run_self_test() ? 0 : 1;
    }

    // Same advisory as vlm-score: the teacher-forced region must be pure text.
    fprintf(stderr, "note: answer-region scoring assumes a pure-text continuation; "
                    "vision tokens after n_prefill (e.g. multi-turn with images in "
                    "later turns) are unsupported and would yield incorrect metrics.\n");

    std::vector<manifest_entry> manifest_entries;
    if (!args.manifest_path.empty() && !read_manifest(args.manifest_path, manifest_entries)) {
        return 1;
    }

    ggml_backend_load_all();

    model_side ref, cand;
    if (!load_side(ref,  "ref",  args.ref_model_path,  args.ref_mmproj_path,  args) ||
        !load_side(cand, "cand", args.cand_model_path, args.cand_mmproj_path, args)) {
        return 1;
    }

    // The metrics compare distributions index-by-index, so both models must
    // share one vocabulary. (Quantizations of the same base model do.)
    const llama_vocab * ref_vocab  = llama_model_get_vocab(ref.model.get());
    const llama_vocab * cand_vocab = llama_model_get_vocab(cand.model.get());
    if (!validate_vocab_id_mapping(ref_vocab, cand_vocab, nullptr,
                                   args.allow_vocab_attr_mismatch)) {
        return 1;
    }
    const int32_t n_vocab = llama_vocab_n_tokens(ref_vocab);

    // Both contexts were created with the same n_batch/n_ctx, so their
    // effective (clamped) batch sizes agree; reconcile via min() anyway.
    const int eff_n_batch = (int) std::min(llama_n_batch(ref.lctx.get()),
                                           llama_n_batch(cand.lctx.get()));

    if (args.manifest_path.empty()) {
        try {
            return score_one(args, ref, cand, n_vocab, eff_n_batch, nullptr) ? 0 : 1;
        } catch (const std::exception & ex) {
            fprintf(stderr, "unhandled exception: %s\n", ex.what());
            return 1;
        }
    }

    bool any_failed = false;
    ggml_log_callback saved_llama_log_callback = nullptr;
    void * saved_llama_log_user_data = nullptr;
    llama_log_get(&saved_llama_log_callback, &saved_llama_log_user_data);

    const size_t n_entries = manifest_entries.size();
    for (size_t i = 0; i < n_entries; ++i) {
        const manifest_entry & e = manifest_entries[i];
        if (!e.ok) {
            fprintf(stderr, "[manifest entry %zu/%zu] %s\n", i + 1, n_entries, e.error.c_str());
            any_failed = true;
            continue;
        }

        stderr_prefix prefix;
        prefix.text = "[row " + std::to_string(i + 1) + "/" + std::to_string(n_entries) + "] ";
        llama_log_set(prefixed_log_callback, &prefix);
        mtmd_helper_log_set(prefixed_log_callback, &prefix);

        vlm_kld_args ea = args;
        ea.image_paths          = e.image_paths;
        ea.formatted_chat_path  = e.formatted_chat_path;
        ea.tokens_in_path       = e.tokens_in_path;
        ea.n_prefill            = e.n_prefill;
        ea.add_special          = e.add_special || args.add_special;
        ea.output_metrics_path  = e.output_metrics_path;
        ea.manifest_path.clear();

        bool row_ok = false;
        const auto t_start = std::chrono::steady_clock::now();
        try {
            row_ok = score_one(ea, ref, cand, n_vocab, eff_n_batch, &prefix);
        } catch (const std::exception & ex) {
            prefixed_fprintf(&prefix, "unhandled exception: %s\n", ex.what());
        }
        const auto t_end = std::chrono::steady_clock::now();
        const double wall_s = std::chrono::duration<double>(t_end - t_start).count();

        llama_log_set(saved_llama_log_callback, saved_llama_log_user_data);
        mtmd_helper_log_set(nullptr, nullptr);

        if (row_ok) {
            fprintf(stderr, "[row] DONE output_metrics=%s wall_s=%.3f\n",
                    e.output_metrics_path.c_str(), wall_s);
        } else {
            any_failed = true;
        }
    }

    return any_failed ? 1 : 0;
}
