"""Interval construction: t (classical paired Student-t, the default),
percentile, BCa, and studentized (bootstrap-t).

All four share the point estimate; t and studentized share the analytic SE
too, and differ only in the critical value. Their measured coverage on
right-skewed per-item deltas with a TRUE delta of zero is tabulated in
docs/compare.md ("Interval construction") and regenerated by
verify_and_validation_scripts/measure_ci_coverage.py -- the t interval's coverage is
equal to or above the bootstrap-t's at n = 25..100 with a narrower interval
and no Monte-Carlo noise, which is why it is the default. These tests pin
the formulas, the closed-form jackknife shortcut, the degenerate fallbacks,
the p-value that inverts each interval, and the plumbing.
"""

import math
from statistics import NormalDist

import numpy as np
import pytest

from stats.contracts import (
    BOOTSTRAP_CI_METHODS,
    CI_METHODS,
    DEFAULT_CI_METHOD,
    NonFiniteMetricError,
    min_bootstrap_iters,
)
from stats.engine import compare_items
from stats.inference import (
    _bootstrap_item_indices,
    _paired_bootstrap_delta,
    _statistic_and_se,
    _two_sided_p,
)
from stats.render import format_comparison_table
from stats.student_t import t_ppf, t_two_sided_p


def _bca_reference(boot, estimate, jack, confidence_level):
    """Efron & Tibshirani's BCa levels, transcribed straight from the
    definition, with no shortcuts."""
    nd = NormalDist()
    z0 = nd.inv_cdf((boot < estimate).mean())
    c = jack.mean() - jack
    a = (c ** 3).sum() / (6.0 * ((c ** 2).sum() ** 1.5))
    alpha = 1.0 - confidence_level
    out = []
    for q in (alpha / 2.0, 1.0 - alpha / 2.0):
        z = nd.inv_cdf(q)
        out.append(nd.cdf(z0 + (z0 + z) / (1.0 - a * (z0 + z))))
    return tuple(out)


def _jackknife_bruteforce(diffs, weights, weighting):
    """Leave-one-out recomputation of the statistic, the slow way."""
    n = diffs.size
    out = []
    for i in range(n):
        keep = np.ones(n, bool)
        keep[i] = False
        d, w = diffs[keep], weights[keep]
        out.append(d.mean() if weighting == "item" else (w * d).sum() / w.sum())
    return np.asarray(out, dtype=float)


def _skewed(n, sigma, seed):
    """Right-skewed per-item deltas with a TRUE mean of zero."""
    rng = np.random.default_rng(seed)
    return np.exp(sigma * rng.standard_normal(n)) - math.exp(sigma ** 2 / 2)


def test_default_ci_method_is_t():
    assert DEFAULT_CI_METHOD == "t"
    assert set(CI_METHODS) == {"t", "studentized", "bca", "percentile"}
    assert set(BOOTSTRAP_CI_METHODS) == {"studentized", "bca", "percentile"}


@pytest.mark.parametrize("weighting", ["item"])
def test_bca_endpoints_match_the_textbook_formula(weighting):
    """And the closed-form jackknife must equal the brute-force leave-one-out
    recomputation of the SAME statistic — that shortcut is the easiest thing
    here to get quietly wrong."""
    d = _skewed(37, 0.9, 4)
    w = np.arange(1, 38, dtype=float) * 3.0
    base = np.zeros_like(d)
    res = _paired_bootstrap_delta(base, d, w, weighting=weighting,
                                     confidence_level=0.95,
                                     bootstrap_iters=2000, seed=11,
                                     ci_method="bca")
    boot = np.array([
        (d[i].mean() if weighting == "item"
         else (w[i] * d[i]).sum() / w[i].sum())
        for i in _bootstrap_item_indices(11, d.size, 2000)])
    estimate = res["estimate"]
    jack = _jackknife_bruteforce(d, w, weighting)
    lo_q, hi_q = _bca_reference(boot, estimate, jack, 0.95)
    want_lo, want_hi = np.quantile(boot, [lo_q, hi_q])
    assert res["ci"]["lower"] == pytest.approx(float(want_lo), rel=1e-12)
    assert res["ci"]["upper"] == pytest.approx(float(want_hi), rel=1e-12)
    assert res["ci"]["ci_method"] == "bca"
    assert "bca_fallback" not in res["ci"]


def test_bca_differs_from_percentile_on_skewed_data():
    d = _skewed(30, 1.0, 7)
    base, w = np.zeros_like(d), np.ones_like(d)
    kw = dict(weighting="item", confidence_level=0.95, bootstrap_iters=2000,
              seed=3)
    pct = _paired_bootstrap_delta(base, d, w, **kw, ci_method="percentile")
    bca = _paired_bootstrap_delta(base, d, w, **kw, ci_method="bca")
    assert pct["estimate"] == bca["estimate"]          # point estimate unchanged
    assert (pct["ci"]["lower"], pct["ci"]["upper"]) != (bca["ci"]["lower"],
                                                       bca["ci"]["upper"])
    assert pct["ci"]["ci_method"] == "percentile"
    assert pct["ci"]["method"].endswith("_percentile")
    assert bca["ci"]["method"].endswith("_bca")


def test_bca_matches_scipy_within_monte_carlo_noise():
    """Independent implementation check against scipy.stats.bootstrap. The two
    draw different resamples, so they agree only to Monte-Carlo noise."""
    scipy_stats = pytest.importorskip("scipy.stats")
    d = _skewed(40, 0.8, 21)
    base, w = np.zeros_like(d), np.ones_like(d)
    ours = _paired_bootstrap_delta(base, d, w, weighting="item",
                                      confidence_level=0.95,
                                      bootstrap_iters=20000, seed=5,
                                      ci_method="bca")
    theirs = scipy_stats.bootstrap((d,), np.mean, method="BCa",
                                   confidence_level=0.95, n_resamples=20000,
                                   random_state=np.random.default_rng(5))
    width = theirs.confidence_interval.high - theirs.confidence_interval.low
    assert abs(ours["ci"]["lower"] - theirs.confidence_interval.low) < 0.05 * width
    assert abs(ours["ci"]["upper"] - theirs.confidence_interval.high) < 0.05 * width


def test_bca_falls_back_to_percentile_on_a_degenerate_sample():
    """Identical per-item deltas: every replicate equals the estimate, so z0
    is +-inf and the jackknife has no spread. BCa is undefined; the interval
    must degrade to percentile and SAY so rather than emit NaNs."""
    d = np.full(8, 0.25)
    base, w = np.zeros_like(d), np.ones_like(d)
    res = _paired_bootstrap_delta(base, d, w, weighting="item",
                                     confidence_level=0.95,
                                     bootstrap_iters=500, seed=1,
                                     ci_method="bca")
    assert res["ci"]["ci_method"] == "percentile"
    assert "degenerate" in res["ci"]["fallback"]
    assert math.isfinite(res["ci"]["lower"]) and math.isfinite(res["ci"]["upper"])
    assert res["ci"]["lower"] == pytest.approx(0.25)


def test_bca_survives_the_two_item_minimum():
    d = np.array([0.1, 0.4])
    base, w = np.zeros_like(d), np.ones_like(d)
    res = _paired_bootstrap_delta(base, d, w, weighting="item",
                                     confidence_level=0.95,
                                     bootstrap_iters=500, seed=2,
                                     ci_method="bca")
    assert math.isfinite(res["ci"]["lower"]) and math.isfinite(res["ci"]["upper"])
    assert res["ci"]["lower"] <= res["estimate"] <= res["ci"]["upper"]


def test_ci_method_is_recorded_and_rejected_when_unknown():
    scores_a = [{"kld": 0.10 + 0.01 * i} for i in range(9)]
    scores_b = [{"kld": 0.11 + 0.02 * i} for i in range(9)]
    w = [10] * 9
    kw = dict(metrics=["kld"], confidence_level=0.95, bootstrap_iters=1000,
              seed=1, model_a_label="A", model_b_label="B")
    res = compare_items(scores_a, scores_b, w, **kw)
    assert res["ci_method"] == "t"
    assert res["metrics"]["kld"]["item_weighted"]["ci_delta"]["ci_method"] == "t"
    res_s = compare_items(scores_a, scores_b, w, **kw, ci_method="studentized")
    assert res_s["ci_method"] == "studentized"
    assert res_s["metrics"]["kld"]["item_weighted"]["ci_delta"]["ci_method"] in {
        "studentized", "percentile"}
    res_p = compare_items(scores_a, scores_b, w, **kw, ci_method="percentile")
    assert res_p["ci_method"] == "percentile"
    with pytest.raises(ValueError, match="ci_method"):
        compare_items(scores_a, scores_b, w, **kw, ci_method="jackknife")


# --------------------------------------------------------------------------- #
# studentized (bootstrap-t)
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("weighting", ["item"])
def test_statistic_and_se_matches_a_direct_computation(weighting):
    """The independent units determine the unweighted mean's standard error."""
    d = np.array([-2., -1., 0., 1., 2.])
    w = np.array([1., 2., 3., 4., 1000.])
    theta, se = _statistic_and_se(d, w, weighting)
    assert theta == 0.0
    assert se == pytest.approx(math.sqrt(0.5))


def test_studentized_interval_is_the_crossed_bootstrap_t_form():
    """[theta - t_(1-a/2) SE, theta - t_(a/2) SE] -- writing the quantiles the
    obvious way round silently yields a percentile-like interval reflected
    through the estimate, which passes most smoke tests."""
    d = _skewed(45, 0.9, 33)
    base, w = np.zeros_like(d), np.ones_like(d)
    res = _paired_bootstrap_delta(base, d, w, weighting="item",
                                     confidence_level=0.95,
                                     bootstrap_iters=3000, seed=8,
                                     ci_method="studentized")
    theta, se = _statistic_and_se(d, w, "item")
    t_star = []
    for idx in _bootstrap_item_indices(8, d.size, 3000):
        th, s = _statistic_and_se(d[idx], w[idx], "item")
        if s > 0:
            t_star.append((th - theta) / s)
    t_star = np.asarray(t_star)
    t_hi, t_lo = np.quantile(t_star, [0.975, 0.025])
    assert res["ci"]["lower"] == pytest.approx(theta - t_hi * se, rel=1e-12)
    assert res["ci"]["upper"] == pytest.approx(theta - t_lo * se, rel=1e-12)
    assert res["ci"]["standard_error"] == pytest.approx(se)


def test_studentized_falls_back_when_there_is_no_spread():
    d = np.full(12, -0.75)
    base, w = np.zeros_like(d), np.ones_like(d)
    res = _paired_bootstrap_delta(base, d, w, weighting="item",
                                     confidence_level=0.95,
                                     bootstrap_iters=1000, seed=1,
                                     ci_method="studentized")
    assert res["ci"]["ci_method"] == "percentile"
    assert "no spread" in res["ci"]["fallback"]


# --------------------------------------------------------------------------- #
# t (classical paired Student-t, no bootstrap)
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("weighting", ["item"])
def test_t_interval_is_the_textbook_paired_t(weighting):
    """theta -+ t_{n-1, 0.975} * SE with the SAME SE the studentized method
    uses (s/sqrt(n) item-weighted),
    and p = P(|T_{n-1}| >= |theta/SE|). scipy is the oracle when present;
    the closed form below is checked regardless."""
    d = _skewed(37, 0.9, 4)
    w = np.arange(1, 38, dtype=float) * 3.0
    base = np.zeros_like(d)
    res = _paired_bootstrap_delta(base, d, w, weighting=weighting,
                                     confidence_level=0.95,
                                     bootstrap_iters=0, seed=None,
                                     ci_method="t")
    theta, se = _statistic_and_se(d, w, weighting)
    q = t_ppf(0.975, 36)
    assert res["estimate"] == theta
    assert res["ci"]["lower"] == pytest.approx(theta - q * se, rel=1e-14)
    assert res["ci"]["upper"] == pytest.approx(theta + q * se, rel=1e-14)
    assert res["ci"]["standard_error"] == se
    assert res["ci"]["degrees_of_freedom"] == 36
    assert res["ci"]["bootstrap_iters"] == 0
    assert res["ci"]["ci_method"] == "t"
    assert res["ci"]["method"] == f"paired_{weighting}_weighted_student_t"
    assert res["bootstrap_std"] is None
    assert "fallback" not in res["ci"]
    assert res["p_value"] == pytest.approx(t_two_sided_p(theta / se, 36), rel=1e-14)
    st = pytest.importorskip("scipy.stats")
    assert q == pytest.approx(st.t.ppf(0.975, 36), rel=1e-10)
    if weighting == "item":
        # the item-weighted case IS scipy's paired t-test
        tt = st.ttest_rel(d, base)
        assert res["p_value"] == pytest.approx(float(tt.pvalue), rel=1e-9)
        lo, hi = tt.confidence_interval(0.95)
        assert res["ci"]["lower"] == pytest.approx(float(lo), rel=1e-9)
        assert res["ci"]["upper"] == pytest.approx(float(hi), rel=1e-9)


def test_t_interval_ignores_seed_and_iters():
    """No replicate is drawn: the result is a pure function of the deltas."""
    d = _skewed(30, 1.0, 7)
    base, w = np.zeros_like(d), np.ones_like(d)
    a = _paired_bootstrap_delta(base, d, w, weighting="item",
                                   confidence_level=0.95, bootstrap_iters=5000,
                                   seed=1, ci_method="t")
    b = _paired_bootstrap_delta(base, d, w, weighting="item",
                                   confidence_level=0.95, bootstrap_iters=0,
                                   seed=99, ci_method="t")
    assert a == b
    assert min_bootstrap_iters(0.95, "t") == 0
    assert min_bootstrap_iters(0.99, "t") == 0


def test_t_interval_is_a_point_on_a_degenerate_sample():
    """Identical deltas (SE = 0): the interval is [theta, theta] and p is the
    SE -> 0 limit of the t test -- 0 when theta != 0, 1 when theta == 0 --
    with the JSON saying why, mirroring the bootstrap methods' zero-spread
    fallback note."""
    d = np.full(12, -0.75)
    base, w = np.zeros_like(d), np.ones_like(d)
    res = _paired_bootstrap_delta(base, d, w, weighting="item",
                                     confidence_level=0.95, bootstrap_iters=0,
                                     seed=None, ci_method="t")
    assert res["ci"]["lower"] == res["ci"]["upper"] == -0.75
    assert res["p_value"] == 0.0
    assert "no spread" in res["ci"]["fallback"]
    assert res["ci"]["ci_method"] == "t"
    zero = _paired_bootstrap_delta(base, np.zeros(12), w, weighting="item",
                                      confidence_level=0.95, bootstrap_iters=0,
                                      seed=None, ci_method="t")
    assert zero["p_value"] == 1.0 and zero["ci"]["contains_zero"]
    with pytest.raises(ValueError, match="at least two"):
        _paired_bootstrap_delta(np.zeros(1), np.ones(1), np.ones(1),
                                weighting="item", confidence_level=0.95,
                                bootstrap_iters=0, seed=None, ci_method="t")


def test_t_interval_plumbs_through_compare_items():
    scores_a = [{"kld": 0.10 + 0.01 * i} for i in range(9)]
    scores_b = [{"kld": 0.11 + 0.02 * i} for i in range(9)]
    w = [10] * 9
    res = compare_items(scores_a, scores_b, w, metrics=["kld"],
                           confidence_level=0.95, bootstrap_iters=1000, seed=1,
                           model_a_label="A", model_b_label="B", ci_method="t")
    assert res["ci_method"] == "t"
    assert res["bootstrap_iters"] == 0
    for weighting in ("item_weighted",):
        cell = res["metrics"]["kld"][weighting]
        assert cell["ci_delta"]["ci_method"] == "t"
        assert cell["ci_delta"]["degrees_of_freedom"] == 8
        assert cell["bootstrap_std"] is None
    md = format_comparison_table(res, reference_label="F16")
    assert "95% CI via paired Student-t (df = n - 1, no bootstrap)" in md
    assert "paired-bootstrap iters" not in md


# --------------------------------------------------------------------------- #
# p-values must invert the interval that was actually built
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("method", ["t", "percentile", "bca", "studentized"])
@pytest.mark.parametrize("weighting", ["item"])
def test_p_value_agrees_with_its_own_interval(method, weighting):
    """"p <= alpha" and "the CI excludes 0" must not be able to disagree,
    which is what lets the Holm column sit beside the CI column."""
    rng = np.random.default_rng(99)
    disagree = 0
    for t in range(60):
        n = int(rng.integers(6, 45))
        d = (np.exp(0.8 * rng.standard_normal(n)) - math.exp(0.32)
             + rng.normal(0.0, 0.4))
        base = np.zeros(n)
        w = rng.integers(5, 60, n).astype(float)
        r = _paired_bootstrap_delta(base, d, w, weighting=weighting,
                                       confidence_level=0.95,
                                       bootstrap_iters=2000, seed=t,
                                       ci_method=method)
        excludes = not (r["ci"]["lower"] <= 0.0 <= r["ci"]["upper"])
        disagree += (r["p_value"] <= 0.05) != excludes
    if method == "t":
        assert disagree == 0            # analytic: the inversion is exact
    else:
        # A handful of boundary cells can differ: the interval interpolates
        # between order statistics while the ASL counts them.
        assert disagree <= 2, disagree


def test_p_value_is_symmetric_under_negation():
    """An all-negative replicate set must report the same p as an
    all-positive one; a one-sided `<=` count alone halves one of them."""
    up = np.full(40, 0.001)
    down = -up
    base, w = np.zeros(40), np.ones(40)
    for method in CI_METHODS:
        a = _paired_bootstrap_delta(base, up, w, weighting="item",
                                       confidence_level=0.95,
                                       bootstrap_iters=2000, seed=1,
                                       ci_method=method)["p_value"]
        b = _paired_bootstrap_delta(base, down, w, weighting="item",
                                       confidence_level=0.95,
                                       bootstrap_iters=2000, seed=1,
                                       ci_method=method)["p_value"]
        assert a == pytest.approx(b), method
        if method == "t":
            assert a == 0.0     # SE = 0 limit; the bootstrap floor 2/(B+1) does not apply
        else:
            assert a > 0.0
    # and on a sample WITH spread the t p-value is symmetric too
    d = _skewed(40, 0.7, 3)
    for sign in (1.0, -1.0):
        r = _paired_bootstrap_delta(base, sign * d, w, weighting="item",
                                       confidence_level=0.95, bootstrap_iters=0,
                                       seed=None, ci_method="t")
        assert r["p_value"] == pytest.approx(
            _paired_bootstrap_delta(base, -sign * d, w, weighting="item",
                                       confidence_level=0.95, bootstrap_iters=0,
                                       seed=None, ci_method="t")["p_value"])


def test_bca_p_value_reduces_to_the_percentile_form_without_correction():
    boot = np.linspace(-1.0, 3.0, 4001)
    plain = _two_sided_p(boot, 1.0, ci_method="percentile")
    reduced = _two_sided_p(boot, 1.0, ci_method="bca", z0=0.0, accel=0.0)
    assert reduced == pytest.approx(plain, rel=0.02)


@pytest.mark.parametrize("method", CI_METHODS)
@pytest.mark.parametrize("weighting", ["item"])
def test_overflowed_standard_error_cannot_become_zero_spread(method, weighting):
    with pytest.raises(NonFiniteMetricError, match="non-finite.*standard error"):
        _paired_bootstrap_delta(np.zeros(3), np.array([1e200, -1e200, 1e200]),
                                np.ones(3), weighting=weighting, confidence_level=0.95,
                                bootstrap_iters=1000, seed=1, ci_method=method)


@pytest.mark.parametrize("weighting", ["item"])
def test_underflowed_standard_error_cannot_become_zero_spread(weighting):
    with pytest.raises(NonFiniteMetricError, match="standard error underflow"):
        _paired_bootstrap_delta(np.zeros(3), np.array([1e-200, -1e-200, 1e-200]),
                                np.ones(3), weighting=weighting, confidence_level=0.95,
                                bootstrap_iters=0, seed=1, ci_method="t")
