#!/usr/bin/env python3
# =============================================================================
# prep_vlm_score_from_hf.py
#
# Translate ONE row of the VLM ground-truth HF dataset into the four
# intermediate files that llama-vlm-kld consumes:
#
#     <out>/img_{i}.png             N PIL images (one per image in the row)
#     <out>/tokens.bin              int32[L] of full input_ids
#     <out>/formatted_chat.txt      Chat string with single <__media__> markers
#                                   (decode-and-collapse of row's input_ids)
#     <out>/meta.json               n_prefill, n_answer, num_images, plus the
#                                   full image_processor_config and a derived
#                                   image_token_limits block (image_min_tokens
#                                   / image_max_tokens for mtmd), ...
#
# Two ways to use it:
#   * CLI (one row):     python3 prep_vlm_score_from_hf.py --row N --out DIR ...
#   * Library (a sweep): collect_kld.py imports prep_row()/load_tokenizer()/
#                        load_dataset_sorted() and prepares every row in-process,
#                        so `import datasets`, load_dataset, sort and the
#                        tokenizer load are paid once per sweep instead of once
#                        per row (the per-row subprocess used to pay them N times).
#
# Supports the model families registered in MODEL_FAMILIES (currently
# Qwen3-VL, Qwen3.5, Qwen3.6, Gemma 4, and Kimi-VL). A new family needs its prefix +
# image-block regex and image-pad token registered below, plus a
# decode->re-tokenize round-trip verification before trusting its dumps.
#
# This dataset carries the full per-row image_processor_config; build_meta()
# records it and derives the mtmd-equivalent --image-min-tokens /
# --image-max-tokens (see derive_image_token_limits). Older datasets that only
# stored image_processor_config_hash are not supported.
#
# Usage:
#   python3 tools/skymizer/prep_vlm_score_from_hf.py \
#       --out tmp/ds-0 \
#       (--row N | --item-id ITEM_ID) \
#       [--dataset elichen-skymizer/qwen3-vl-4b-instruct-ground-truth-vllm] \
#       [--subset mmmu-pro-standard-10-sample-100] \
#       [--split train] \
#       [--sort-by num_images]
#
# Example:
#   --row 0      → smallest num_images sample after sorting
#   --row -1     → largest num_images sample
#   --item-id test_Physics_353
#
# Exit codes (CLI):
#   0 = success
#   non-zero = sanity check failed (with explicit message). Common causes:
#   marker count mismatch, n_prefill out of range, unregistered model family.
#
# Rows generated by llama-server (generation_engine == "llama.cpp", schema
# v1.4 of llm_reference_generator) skip decode-and-collapse entirely: they
# carry the exact `llamacpp_prompt_string` (canonical <__media__> markers)
# the generator sent, the raw image bytes it sent (`image_bytes_sha256`),
# and the server's own `llamacpp_n_past_prefill`. prep copies those through
# verbatim so the scorer's mtmd prefix is the generation prefix; collect
# compares the scorer's n_past_actual against n_past_expected and WARNS on
# drift (producer and consumer llama.cpp need not be the same build).
#
# Design rationale (decode-and-collapse vs apply_chat_template): the prefill
# is reconstructed by DECODING the stored input_ids[:n_prefill] (then folding
# each expanded image-placeholder block back to one marker), never by re-
# rendering the chat template — re-rendering could drift from the tokens the
# generator actually consumed. tokens.bin is the full input_ids verbatim.
# =============================================================================

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import numpy as np

# `datasets` and `transformers` are imported lazily (inside load_dataset_sorted
# and load_tokenizer) so prep_row() and the validation helpers stay importable
# for hermetic unit tests, which run with only numpy installed.


class PrepError(ValueError):
    """A row cannot be turned into scorer inputs: wrong model family, image
    marker count mismatch, or inconsistent prefill/answer lengths. Raised
    instead of sys.exit so an in-process caller (collect_kld.py) can record
    one row as FAILED and keep sweeping; the CLI translates it to a non-zero
    exit in main()."""


# How build_formatted_chat hands image wrappers to mtmd. "stripped" = the whole
# <|vision_start|>(<|image_pad|>)+<|vision_end|> block collapses to one
# <__media__> and mtmd re-adds the wrapper pair itself (mtmd.cpp add_media),
# so the scorer's token stream matches HF/vLLM exactly (Qwen, Gemma-4; for
# Kimi-VL the collapsed block also holds a two-token prelude mtmd never emits,
# see _KIMI_VL_IMAGE_BLOCK_RE). Dumps collected before
# this change kept the wrappers in the text, which mtmd then duplicated
# ("doubled": 2 extra tokens per image, ~0.016 KLD shift). Recorded in
# collect_meta.json as a compare / shard-identity field — dirs collected under
# different modes saw different conditioning and must not be compared.
MEDIA_WRAPPER_MODE = "stripped"


def load_dataset_sorted(dataset, subset, split, sort_by, sort_desc=False):
    """Load and (optionally) sort the dataset. Lazy `datasets` import so the
    module stays importable without it.

    `dataset` is either a Hub repo id (subset optional: when falsy the dataset
    is loaded without a config name) or a LOCAL `Dataset.save_to_disk`
    directory (the generators' --save_path output; has a `state.json`), which
    is loaded with `load_from_disk` so a collection scores exactly the rows the
    generator wrote, immune to the Hub subset being re-pushed meanwhile. A
    saved DatasetDict is indexed by `split`; a saved Dataset ignores it.
    sort_desc mirrors prep_llm_score_from_hf: default False keeps every
    existing index-keyed artifact dir valid."""
    from datasets import load_dataset
    local = Path(dataset)
    if (local / "state.json").is_file() or (local / "dataset_dict.json").is_file():
        from datasets import DatasetDict, load_from_disk
        if subset:
            raise ValueError(f"--subset {subset!r} does not apply to the local dataset dir {dataset}")
        ds = load_from_disk(str(local))
        if isinstance(ds, DatasetDict):
            ds = ds[split]
    else:
        ds = (load_dataset(dataset, subset, split=split) if subset
              else load_dataset(dataset, split=split))
    if sort_by:
        if sort_desc:
            ds = ds.sort([sort_by], reverse=True)
        else:
            ds = ds.sort([sort_by])
    return ds


# Model-name prefixes (a subset of MODEL_FAMILIES) whose HF tokenizer is
# repository code (tokenizer_config auto_map), which AutoTokenizer refuses to
# run without trust_remote_code. Kimi-VL ships
# tokenization_moonshot.TikTokenTokenizer, which imports `tiktoken` (whose
# vocab loader in turn imports `blobfile`); both are project dependencies
# for that reason. Every other family loads with trust_remote_code=False so
# a stray auto_map in a new model fails immediately instead of prompting.
REMOTE_CODE_TOKENIZER_PREFIXES = ("moonshotai/Kimi-VL",)


def tokenizer_trusts_remote_code(model_name):
    """Whether load_tokenizer must pass trust_remote_code for this model."""
    return model_name.startswith(REMOTE_CODE_TOKENIZER_PREFIXES)


def load_tokenizer(model_name):
    """Load the HF tokenizer used only to decode input_ids back to text. Lazy
    `transformers` import so the module stays importable without it.
    trust_remote_code is opt-in per family (REMOTE_CODE_TOKENIZER_PREFIXES)."""
    from transformers import AutoTokenizer
    return AutoTokenizer.from_pretrained(
        model_name, trust_remote_code=tokenizer_trusts_remote_code(model_name))


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dataset", default="elichen-skymizer/qwen3-vl-4b-instruct-ground-truth-vllm")
    p.add_argument("--subset",  default="mmmu-pro-standard-10-sample-100")
    p.add_argument("--split",   default="train")
    p.add_argument("--sort-by", default="num_images")
    sel = p.add_mutually_exclusive_group(required=True)
    sel.add_argument("--row", type=int)
    sel.add_argument("--item-id", type=str)
    p.add_argument("--out", required=True, type=Path)
    return p.parse_args()


def pick_row(ds, args):
    if args.row is not None:
        return ds[args.row]
    matches = [i for i, x in enumerate(ds["item_id"]) if x == args.item_id]
    if not matches:
        sys.exit(f"item_id {args.item_id!r} not found")
    return ds[matches[0]]


# Family registry: model-name prefix -> regex collapsing one image's expanded
# placeholder block (as decoded from input_ids) to a single <__media__> marker.
# Registering a prefix here asserts two facts verified for that family:
# (a) its HF processor emits exactly this wrapped block per image, and (b) the
# wrappers must be stripped because mtmd re-adds them (see MEDIA_WRAPPER_MODE).
# Qwen3.5 reuses Qwen3-VL's wrapper *strings* — the token IDs differ (248053+
# vs 151652+) but prep operates on decoded text, so only the strings matter.
_QWEN_VL_IMAGE_BLOCK_RE = re.compile(
    r"<\|vision_start\|>(?:<\|image_pad\|>)+<\|vision_end\|>")

# Gemma 4 rows from elichen-skymizer/ground-truth-mmmu-pro-vision decode each
# image as <|image>(<|image|>)+<image|>. ../mtmd/mtmd.cpp:479-485 shows gemma4v
# re-injecting <|image>/<image|>, so stripped wrapper mode is correct.
_GEMMA4_IMAGE_BLOCK_RE = re.compile(
    r"<\|image>(?:<\|image\|>)+<image\|>")

# Kimi-VL rows (elichen-skymizer/kimi-vl-a3b-ins-full-ref-text-*) decode each
# image as <|media_start|>image<|media_content|>(<|media_pad|>)+<|media_end|>:
# the chat template's literal block, with the HF processor expanding the
# single <|media_pad|> to one per vision token. ../mtmd/mtmd.cpp
# (PROJECTOR_TYPE_KIMIVL) re-injects only <|media_start|>/<|media_end|>
# around the embeddings, so the WHOLE block -- including the
# `image<|media_content|>` prelude mtmd never emits -- collapses to one
# marker. llama.cpp therefore conditions on two fewer text tokens per image
# than HF did, and on a vision-token count that differs in either direction
# (see derive_image_token_limits); the paired comparison cancels it because
# both sides see the same prefix, and every record's n_past_actual keeps
# the per-row drift visible. Verified 2026-09-03: decode -> re-encode of
# input_ids[:n_prefill] exact outside the pad run on all 954 rows of both
# kimi-vl-a3b-ins-full-ref-text datasets; llama.cpp tokenization of the
# collapsed text equals the HF ids on 60 text segments of 30 rows; a 4-row
# collect_kld smoke (bf16 ref vs Q4_K_M + mmproj-Q8_0) scored every row
# (e.g. n_past 476 for n_prefill 489: -2 prelude, -11 grid rounding).
_KIMI_VL_IMAGE_BLOCK_RE = re.compile(
    r"<\|media_start\|>image<\|media_content\|>(?:<\|media_pad\|>)+<\|media_end\|>")

MODEL_FAMILIES = {
    "Qwen/Qwen3-VL": _QWEN_VL_IMAGE_BLOCK_RE,
    "Qwen/Qwen3.5":  _QWEN_VL_IMAGE_BLOCK_RE,
    # Qwen3.6 verified like Qwen3.5 (2026-08-27, GAP qwen3.6-35b-a3b rows):
    # decoded blocks are <|vision_start|>(<|image_pad|>)+<|vision_end|> with
    # pad count == sum_vision_tokens, and the mmproj projector is
    # qwen3vl_merger, so mtmd re-adds the same wrappers.
    "Qwen/Qwen3.6":  _QWEN_VL_IMAGE_BLOCK_RE,
    "google/gemma-4": _GEMMA4_IMAGE_BLOCK_RE,
    "moonshotai/Kimi-VL": _KIMI_VL_IMAGE_BLOCK_RE,
}

# Per-image placeholder token (string form), keyed by model-name prefix.
# Resolved through resolve_image_pad_id() so a tokenizer lacking the
# family-specific token fails loudly instead of silently mapping to the unk id.
IMAGE_PAD_TOKENS = {
    "Qwen/Qwen3-VL": "<|image_pad|>",
    "Qwen/Qwen3.5":  "<|image_pad|>",
    "Qwen/Qwen3.6":  "<|image_pad|>",
    "google/gemma-4": "<|image|>",
    "moonshotai/Kimi-VL": "<|media_pad|>",
}


def _family_value_for(registry, model_name):
    """Resolve a model-prefix registry with longest-prefix-wins semantics."""
    for prefix in sorted(registry, key=len, reverse=True):
        if model_name.startswith(prefix):
            return registry[prefix]
    raise PrepError(
        f"unsupported model family: {model_name!r}; "
        f"known prefixes: {sorted(registry)}")


def image_block_regex_for(model_name):
    """The collapse regex for the row's model family, or PrepError if the
    family was never verified against this pipeline (wrapper scheme and
    round-trip behavior are per-family facts, not guessable defaults).
    Longest prefix wins, so an overlapping more-specific entry beats a
    shorter one regardless of registration order."""
    return _family_value_for(MODEL_FAMILIES, model_name)


def image_pad_token_for(model_name):
    """The placeholder token string for a registered model family."""
    return _family_value_for(IMAGE_PAD_TOKENS, model_name)


def resolve_image_pad_id(tokenizer, model_name):
    """The family-specific image-pad token id, validated by round-trip.

    HF fast tokenizers return the unk id (not None) for a missing token, so a
    bare convert_tokens_to_ids() on an unsupported family would silently count
    or mask the wrong tokens downstream."""
    image_pad_token = image_pad_token_for(model_name)
    token_id = tokenizer.convert_tokens_to_ids(image_pad_token)
    if (not isinstance(token_id, int)
            or tokenizer.convert_ids_to_tokens(token_id) != image_pad_token):
        raise PrepError(
            f"tokenizer has no {image_pad_token} token "
            f"(convert_tokens_to_ids returned {token_id!r}); this model "
            f"family's image placeholder scheme is not supported")
    return token_id


LLAMACPP_ENGINE = "llama.cpp"
CANONICAL_MEDIA_MARKER = "<__media__>"


def is_llamacpp_row(row) -> bool:
    """True for rows produced by the llama-server ground-truth backend."""
    return row.get("generation_engine") == LLAMACPP_ENGINE


def llamacpp_formatted_chat(row) -> str:
    """The prompt string the generator sent to llama-server, with markers
    normalized to mtmd's default so the scorer tokenizes the same text."""
    prompt = row.get("llamacpp_prompt_string")
    if not isinstance(prompt, str) or not prompt:
        raise PrepError("llama.cpp row lacks llamacpp_prompt_string")
    marker = row.get("llamacpp_media_marker") or CANONICAL_MEDIA_MARKER
    if marker != CANONICAL_MEDIA_MARKER:
        if CANONICAL_MEDIA_MARKER in prompt:
            raise PrepError(
                f"llamacpp_prompt_string contains both {marker!r} and "
                f"{CANONICAL_MEDIA_MARKER!r}; cannot normalize markers")
        prompt = prompt.replace(marker, CANONICAL_MEDIA_MARKER)
    n_markers = prompt.count(CANONICAL_MEDIA_MARKER)
    if n_markers != row["num_images"]:
        raise PrepError(f"marker count {n_markers} != num_images {row['num_images']}")
    return prompt


_IMAGE_MAGIC = (
    (b"\x89PNG\r\n\x1a\n", "png"),
    (b"\xff\xd8", "jpg"),
    (b"GIF87a", "gif"),
    (b"GIF89a", "gif"),
    (b"BM", "bmp"),
)


def image_extension(data: bytes) -> str:
    """File extension for raw encoded image bytes (mtmd sniffs content; the
    extension only keeps the prep dir honest)."""
    for magic, ext in _IMAGE_MAGIC:
        if data.startswith(magic):
            return ext
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "webp"
    return "bin"


class RawImageReader:
    """Raw encoded bytes of every image in a dataset, keyed by item_id.

    llama.cpp rows must be scored on the bytes the generator sent (stb_image
    decodes them identically), not on a PIL re-encode; the HF `Image`
    feature only hands out decoded PIL objects, so this keeps a
    `decode=False` view of the same table."""

    def __init__(self, ds, images_col: str = "images"):
        from datasets import Image, Sequence
        self._view = ds.cast_column(images_col, Sequence(Image(decode=False)))
        self._images_col = images_col
        self._index = {item_id: i for i, item_id in enumerate(ds["item_id"])}

    def get(self, item_id) -> list:
        idx = self._index[item_id]
        out = []
        for entry in self._view[idx][self._images_col]:
            data = entry.get("bytes") if isinstance(entry, dict) else None
            if data is None:
                path = entry.get("path") if isinstance(entry, dict) else None
                if not path:
                    raise PrepError(f"{item_id}: image has neither bytes nor path")
                data = Path(path).read_bytes()
            out.append(bytes(data))
        return out


def build_formatted_chat(row, tok):
    """Decode-and-collapse: lossless reconstruction of the formatted chat
    string from input_ids, then fold each expanded image placeholder block
    (per the family's registered regex) to a single <__media__> marker
    (mtmd's default media marker). The wrappers are
    swallowed too because mtmd owns them at eval time: add_media injects its
    own <|vision_start|>/<|vision_end|> pair around the image embeddings, so
    leaving them in the text would double-wrap every image (2 extra tokens per
    image vs the HF/vLLM conditioning). The regex requires the complete
    wrapped block — a bare pad run without wrappers produces no marker and
    fails the count check below instead of being silently accepted. The
    tokenizer is supplied by the caller so a sweep loads it once, not once
    per row. llama.cpp rows bypass all of this: their prompt string is stored
    verbatim (see llamacpp_formatted_chat)."""
    if is_llamacpp_row(row):
        return llamacpp_formatted_chat(row)
    model_name = row["generation_model_name_or_path"]
    image_block_re = image_block_regex_for(model_name)
    n_prefill = row["n_prefill_tokens"]
    raw = tok.decode(row["input_ids"][:n_prefill], skip_special_tokens=False)
    formatted = image_block_re.sub("<__media__>", raw)
    n_markers = formatted.count("<__media__>")
    if n_markers != row["num_images"]:
        raise PrepError(f"marker count {n_markers} != num_images {row['num_images']}")
    return formatted


def sanity_check_row(row):
    L = row["input_tokens_len"]
    n_pre = row["n_prefill_tokens"]
    n_ans = row["generated_tokens_len"]
    if len(row["input_ids"]) != L:
        raise PrepError(f"len(input_ids)={len(row['input_ids'])} != input_tokens_len={L}")
    if not (0 < n_pre < L):
        raise PrepError(f"n_prefill_tokens={n_pre} out of range for L={L}")
    if n_pre + n_ans != L:
        raise PrepError(f"n_prefill({n_pre}) + n_answer({n_ans}) != L({L})")
    # Labels rules R4-R6, mirroring prep_llm_score_from_hf: the C++ scorers
    # take targets from input_ids[n_prefill:], so a row whose stored labels
    # disagree with that suffix would be scored against different tokens per
    # runtime — refuse it here instead of exporting a hash that asserts the
    # wrong content.
    labels = row["labels"]
    if len(labels) != L:
        raise PrepError(f"len(labels)={len(labels)} != input_tokens_len={L}")
    if any(int(x) != -100 for x in labels[:n_pre]):
        raise PrepError("labels[:n_prefill] must all be -100")
    if [int(x) for x in labels[n_pre:]] != [int(x) for x in row["input_ids"][n_pre:]]:
        raise PrepError("labels[n_prefill:] must equal input_ids[n_prefill:]")


def derive_image_token_limits(cfg: dict) -> dict:
    """Derive mtmd vision bounds from a recognized image-processor schema.

    Qwen configs express pixel-area bounds which are inverted through patch and
    merge sizes. Gemma 4 configs directly record max_soft_tokens; their
    image_min_tokens=-1 means use the model metadata's lower bound. Kimi-VL
    configs cap the PRE-merge patch count (in_token_limit) and merge
    merge_kernel_size patches per vision token, so image_max_tokens is
    in_token_limit // (kh * kw). The HF processor never upscales, so the
    derived lower bound is 1 token: -1 would hand the floor to mtmd, and for
    kimivl clip.cpp hard-codes 8..1024 (no mmproj metadata), which scales
    images HF left below 8 tokens UP (a 77x16 OCR crop: 3 HF tokens vs 14).
    The cap is not a per-row upper bound either: the HF rescale floors to
    in_token_limit and then pads each side up to a merge-kernel multiple, so
    rows carry MORE vision tokens than the cap (1100 observed in the GAP
    rows, ~1.16x possible), while mtmd's dyn_size resize (nearest-multiple
    rounding) yields yet another count -- accepted, common-mode drift,
    see the _KIMI_VL_IMAGE_BLOCK_RE comment. The additional per-family
    fields are provenance records: collectors default to -1/-1 and only
    explicit token-limit arguments affect mtmd."""
    if not isinstance(cfg, dict):
        raise PrepError("unsupported image processor config schema")

    if cfg.get("engine") == LLAMACPP_ENGINE:
        # llama-server rows record the budget mtmd was launched with (-1 =
        # the projector's own default); there is no HF geometry to invert.
        return {
            "engine": LLAMACPP_ENGINE,
            "image_min_tokens": int(cfg.get("image_min_tokens", -1)),
            "image_max_tokens": int(cfg.get("image_max_tokens", -1)),
            "llama_cpp_build": cfg.get("llama_cpp_build"),
            "mmproj_sha256": cfg.get("mmproj_sha256"),
        }

    ip = cfg.get("hf_image_processor")
    if not isinstance(ip, dict):
        ip = {}

    if "merge_size" in ip:
        try:
            patch_size = int(ip["patch_size"])
            merge_size = int(ip["merge_size"])
            size = ip.get("size", {})
            min_pixels = int(ip.get("min_pixels", size.get("shortest_edge")))
            max_pixels = int(ip.get("max_pixels", size.get("longest_edge")))
        except (AttributeError, KeyError, TypeError, ValueError) as exc:
            raise PrepError(
                "invalid Qwen image processor config schema") from exc
        patch_area = patch_size * patch_size * merge_size * merge_size
        return {
            "patch_size": patch_size,
            "merge_size": merge_size,
            "min_pixels": min_pixels,
            "max_pixels": max_pixels,
            "image_min_tokens": min_pixels // patch_area,
            "image_max_tokens": max_pixels // patch_area,
        }

    gemma_vision_cfg = cfg.get("gemma4_vision_token_config")
    is_gemma4 = (
        ip.get("image_processor_type") == "Gemma4ImageProcessor"
        or isinstance(gemma_vision_cfg, dict)
    )
    if is_gemma4:
        source = dict(ip)
        if isinstance(gemma_vision_cfg, dict):
            source.update(gemma_vision_cfg)
        try:
            patch_size = int(source["patch_size"])
            pooling_kernel_size = int(source["pooling_kernel_size"])
            max_soft_tokens = int(source["max_soft_tokens"])
        except (KeyError, TypeError, ValueError) as exc:
            raise PrepError(
                "invalid Gemma 4 image processor config schema") from exc
        return {
            "patch_size": patch_size,
            "pooling_kernel_size": pooling_kernel_size,
            "max_soft_tokens": max_soft_tokens,
            "image_min_tokens": -1,
            "image_max_tokens": max_soft_tokens,
        }

    kimi_vision_cfg = cfg.get("kimi_vl_vision_token_config")
    is_kimi_vl = (
        ip.get("image_processor_type") == "KimiVLImageProcessor"
        or isinstance(kimi_vision_cfg, dict)
    )
    if is_kimi_vl:
        source = dict(ip)
        if isinstance(kimi_vision_cfg, dict):
            source.update(kimi_vision_cfg)
        kernel = source.get("merge_kernel_size")
        if not isinstance(kernel, (list, tuple)) or len(kernel) != 2:
            raise PrepError("invalid Kimi-VL image processor config schema: "
                            f"merge_kernel_size must be a 2-item list, got {kernel!r}")
        values = {
            "patch_size": source.get("patch_size"),
            "in_token_limit": source.get("in_token_limit"),
            "merge_kernel_size[0]": kernel[0],
            "merge_kernel_size[1]": kernel[1],
        }
        # Exact ints only: a bool, float or numeric string here means the
        # producer changed its schema and provenance would be silently wrong.
        for name, v in values.items():
            if isinstance(v, bool) or not isinstance(v, int) or v <= 0:
                raise PrepError("invalid Kimi-VL image processor config schema: "
                                f"{name} must be a positive int, got {v!r}")
        patch_size = values["patch_size"]
        in_token_limit = values["in_token_limit"]
        merge_h, merge_w = values["merge_kernel_size[0]"], values["merge_kernel_size[1]"]
        image_max_tokens = in_token_limit // (merge_h * merge_w)
        if image_max_tokens < 1:
            raise PrepError("invalid Kimi-VL image processor config schema: "
                            f"in_token_limit {in_token_limit} is below one "
                            f"{merge_h}x{merge_w} merge kernel")
        return {
            "patch_size": patch_size,
            "merge_kernel_size": [merge_h, merge_w],
            "in_token_limit": in_token_limit,
            "image_min_tokens": 1,
            "image_max_tokens": image_max_tokens,
        }

    raise PrepError("unsupported image processor config schema")


def build_meta(row) -> dict:
    """The meta.json payload collect_kld.py reads back (n_prefill / n_answer
    / num_images drive the manifest + target slicing).

    image_processor_config is the full processor config the vLLM ground truth
    was generated with; image_token_limits are the mtmd-equivalent per-image
    vision bounds derived from it (see derive_image_token_limits)."""
    image_processor_config = json.loads(row["image_processor_config"])
    return {
        "item_id": row["item_id"],
        "source": row["source"],
        "category": row["category"],
        "n_prefill": int(row["n_prefill_tokens"]),
        "n_answer":  int(row["generated_tokens_len"]),
        "input_tokens_len": int(row["input_tokens_len"]),
        "num_images": int(row["num_images"]),
        "sum_vision_tokens": int(row["sum_vision_tokens"]),
        "max_vision_tokens": int(row["max_vision_tokens"]),
        "model": row["generation_model_name_or_path"],
        "image_processor_config_hash": row["image_processor_config_hash"],
        "image_processor_config": image_processor_config,
        "image_token_limits": derive_image_token_limits(image_processor_config),
        "ref_answer": row.get("ref_answer"),
        "generated_texts_preview": row["generated_texts"][:200],
        "dataset_seed": int(row["seed"]),
        "generation_engine": row.get("generation_engine"),
        # llama.cpp rows: the server's position count after prefill, the
        # collector's n_past_expected (warn-only cross-check vs the scorer).
        "n_past_expected": (int(row["llamacpp_n_past_prefill"])
                            if is_llamacpp_row(row) else None),
        # llama-server tokenizes /completion prompts with add_special=true; the
        # scorer must replay the same flag or BOS-adding vocabs (Gemma) shift the
        # whole prefix. Rows predating the column were Qwen (no BOS) -> false.
        "add_special": (bool(row.get("llamacpp_add_special", False))
                        if is_llamacpp_row(row) else False),
        "per_image_vision_token_counts": (
            [int(c) for c in row["per_image_vision_token_counts"]]
            if is_llamacpp_row(row) and row.get("per_image_vision_token_counts") is not None
            else None),
    }


def write_prep_images(row, out_dir: Path, raw_images=None) -> list:
    """Write the row's images into out_dir; return their file names.

    With `raw_images` (list of encoded bytes) the bytes are written verbatim
    under a sniffed extension and, when the row carries `image_bytes_sha256`,
    verified against it — the llama.cpp path, where the scorer must decode
    exactly what the generator decoded. Otherwise PIL re-encodes to PNG
    (lossless for the pixels PIL decoded, the historical behaviour)."""
    names = []
    if raw_images is None and is_llamacpp_row(row):
        raise PrepError(
            "llama.cpp-generated rows must be prepped from their raw image bytes "
            "(RawImageReader); a PIL re-encode would not reproduce the generator's "
            "stb_image input")
    if raw_images is not None:
        if len(raw_images) != len(row["images"]):
            raise PrepError(f"{len(raw_images)} raw images for {len(row['images'])} row images")
        expected = row.get("image_bytes_sha256")
        for i, data in enumerate(raw_images):
            if expected is not None:
                digest = hashlib.sha256(data).hexdigest()
                if digest != expected[i]:
                    raise PrepError(
                        f"image {i}: sha256 {digest} != image_bytes_sha256 {expected[i]} "
                        "(dataset image bytes differ from what the generator sent)")
            name = f"img_{i}.{image_extension(data)}"
            (out_dir / name).write_bytes(data)
            names.append(name)
        return names
    for i, img in enumerate(row["images"]):
        name = f"img_{i}.png"
        img.save(out_dir / name)
        names.append(name)
    return names


def prep_row(row, tok, out_dir: Path, raw_images=None) -> dict:
    """Write the four scorer inputs for one dataset row into out_dir and return
    the meta dict (also written to meta.json).

    Pure with respect to framework setup: the caller supplies the already-loaded
    row and tokenizer, so this does only validation + file IO. Raises PrepError
    if the row fails validation (caller decides whether to skip or abort).
    `raw_images` (encoded bytes per image) makes the image files byte-exact
    copies of the dataset's; llama.cpp rows should always get them."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sanity_check_row(row)

    # (1) images -> files (raw bytes when supplied, else PNG re-encode)
    image_files = write_prep_images(row, out_dir, raw_images)

    # (2) input_ids -> int32 binary
    np.asarray(row["input_ids"], dtype=np.int32).tofile(out_dir / "tokens.bin")

    # (3) formatted_chat.txt (decode + collapse)
    formatted = build_formatted_chat(row, tok)
    (out_dir / "formatted_chat.txt").write_text(formatted, encoding="utf-8")

    # (4) meta.json
    meta = build_meta(row)
    meta["image_files"] = image_files
    (out_dir / "meta.json").write_text(
        json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    return meta


def main():
    args = parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    print(f"loading {args.dataset} :: {args.subset} :: {args.split}", file=sys.stderr)
    ds = load_dataset_sorted(args.dataset, args.subset, args.split, args.sort_by)
    row = pick_row(ds, args)
    print(f"selected item_id={row['item_id']!r}  num_images={row['num_images']}  "
          f"L={row['input_tokens_len']}  n_prefill={row['n_prefill_tokens']}",
          file=sys.stderr)

    try:
        tok = load_tokenizer(row["generation_model_name_or_path"])
    except Exception as e:   # transformers raises ValueError/OSError variants
        sys.exit(f"tokenizer load failed for "
                 f"{row['generation_model_name_or_path']!r}: {e}")
    try:
        raw_images = RawImageReader(ds).get(row["item_id"]) if is_llamacpp_row(row) else None
        meta = prep_row(row, tok, args.out, raw_images=raw_images)
    except PrepError as e:
        sys.exit(str(e))

    print(f"wrote {meta['num_images']} image(s), tokens.bin, formatted_chat.txt, "
          f"meta.json", file=sys.stderr)
    print(f"prep complete -> {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
