#!/usr/bin/env python3
"""Measured coverage of every --ci-method on right-skewed paired per-item
deltas whose TRUE delta is zero, driving the production code path
(compare.inference._build_weighting_block) -- the study behind the table in
docs/compare.md ("Interval construction").

    python3 review-functionality/measure_ci_coverage.py \
        [--sims 1000] [--iters 4000] [--n 25 50 100] [--skew 2.3 6.2] \
        [--seed 0] [--out coverage.md]

Generator. Per item a latent "difficulty" a_i = exp(sigma z_i) (lognormal,
the shape of per-item KLD levels) and a paired delta

    d_i = a_i * (exp(tau e_i) - exp(tau^2 / 2)),   z_i, e_i ~ N(0, 1)

which has E[d_i] = 0 exactly and a right tail driven by the few hard items
-- the mechanism that makes a KLD comparison's sample mean sit BELOW the
truth whenever the rare catastrophic items are under-sampled. (sigma, tau)
are calibrated on a large draw so the delta's sample skewness hits each
requested --skew.

Reported per (n, skew, method): coverage of the nominal 95% interval,
misses above / below the truth, and mean width relative to the t interval.
Miss-low means the whole interval sat below 0 -- the side a right-skewed
delta fails on. Every method sees the identical samples.

Deterministic: --seed fixes the calibration draw and every simulated
sample; the bootstrap methods draw their replicates from seed s for sample
s, exactly as a report with --seed s would."""
import argparse
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from compare.contracts import CI_METHODS         # noqa: E402
from compare.inference import _build_weighting_block  # noqa: E402

GRID = [(s, t) for s in (0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
        for t in (0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)]


def skewed_null(rng, n, sigma, tau):
    a = np.exp(sigma * rng.standard_normal(n))
    d = a * (np.exp(tau * rng.standard_normal(n)) - np.exp(tau ** 2 / 2.0))
    return a, d


def sample_skewness(x):
    c = x - x.mean()
    return float((c ** 3).mean() / (c ** 2).mean() ** 1.5)


def calibrate(target, seed):
    rng = np.random.default_rng(seed)
    best = None
    for sigma, tau in GRID:
        sk = sample_skewness(skewed_null(rng, 300_000, sigma, tau)[1])
        if best is None or abs(sk - target) < abs(best[2] - target):
            best = (sigma, tau, sk)
    return best


def run(args):
    methods = list(CI_METHODS)
    rows = []
    for target in args.skew:
        sigma, tau, measured = calibrate(target, args.seed)
        print(f"skew target {target}: sigma={sigma} tau={tau} measured {measured:.2f}",
              file=sys.stderr)
        for n in args.n:
            t0 = time.time()
            stats = {m: {"cov": 0, "lo": 0, "hi": 0, "w": 0.0} for m in methods}
            for s in range(args.sims):
                a, d = skewed_null(np.random.default_rng(args.seed * 1_000_003 + s),
                                   n, sigma, tau)
                b = a + d
                w = np.full(n, 100.0)
                for m in methods:
                    blk = _build_weighting_block(
                        a, b, w, weighting="item",
                        score_direction="lower_is_better",
                        confidence_level=0.95, bootstrap_iters=args.iters,
                        seed=s, ci_method=m, equivalence_margin=None)
                    lo, hi = blk["ci_delta"]["lower"], blk["ci_delta"]["upper"]
                    st = stats[m]
                    st["cov"] += (lo <= 0.0 <= hi)
                    st["lo"] += (hi < 0.0)
                    st["hi"] += (lo > 0.0)
                    st["w"] += hi - lo
            rows.append((n, measured, stats))
            print(f"  n={n}: " + "  ".join(
                f"{m} {stats[m]['cov'] / args.sims:.3f}" for m in methods)
                + f"  ({time.time() - t0:.0f}s)", file=sys.stderr)
    return methods, rows


def render(methods, rows, args):
    out = [f"Nominal 95% interval, true delta 0, {args.sims} simulations, "
           f"`--bootstrap-iters {args.iters}` for the bootstrap methods, "
           "item weighting (`coverage (misses above / below the truth)`; "
           "width relative to `t`):", ""]
    out.append("| n | skew | " + " | ".join(methods) + " |")
    out.append("|---|---|" + "---|" * len(methods))
    for n, sk, stats in rows:
        wt = stats["t"]["w"]
        cells = []
        for m in methods:
            st = stats[m]
            cells.append(f"{st['cov'] / args.sims:.3f} "
                         f"({st['hi'] / args.sims:.3f}/{st['lo'] / args.sims:.3f})"
                         + ("" if m == "t" else f" ×{st['w'] / wt:.2f}"))
        out.append(f"| {n} | {sk:.1f} | " + " | ".join(cells) + " |")
    out.append("")
    out.append(f"Generated by `review-functionality/measure_ci_coverage.py "
               f"--sims {args.sims} --iters {args.iters} --seed {args.seed}`.")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--sims", type=int, default=1000)
    ap.add_argument("--iters", type=int, default=4000)
    ap.add_argument("--n", type=int, nargs="+", default=[25, 50, 100])
    ap.add_argument("--skew", type=float, nargs="+", default=[2.3, 6.2])
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args(argv)
    methods, rows = run(args)
    text = render(methods, rows, args)
    if args.out:
        args.out.write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
